import Head from 'next/head';

import Navbar from '../components/Navbar';
import Header from '../components/Header';
import Proyectos from '../components/Projects';
import Footer from '../components/Footer';
import About from '../components/About';
import Projects from '../components/Projects';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mi portafolio - Mooenz</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <Navbar />
      <Header />
      <About />
      <Projects />
      <Footer />
    </div>
  );
}
